### ISSUE TITLE
can't read file /*DIRECTORY*/3rdperson/meshes/robotMESH.mta

### ISSUE THREAD

**Issue by retep686** [SysStudio/3rdperson#1]
The engine will try and fail to load this file (which doesn't exist) when loading in the robot. Also, the origin on the robot is off, and needs to be reajusted in blender.

**Comment by brycehenley** [comment]
I just fixed the origin, im uploading the fixed model now.

**Comment by brycehenley** [comment]
I think mta has something to do with material animation, or texturing. It is just a warning, so we can ignore it for now.

**Comment by brycehenley** [comment]
I placed the origin point on the model, but it did not fix it in the engine. I think it may be using the center of the scene.

**Comment by brycehenley** [comment]
Alright the origin is good now. for future refrence the center of the blender scene is the orgin of the exported model.

**Comment by brycehenley** [comment]
Since we don't have any material animations on the model this is just a warning we can ignore.
